### ISSUE TITLE
Implement functionality to trigger downstream jobs when the uptream job finishes

### ISSUE THREAD

**Issue by adusca** [mozilla/pulse_actions#6]
- We store somewhere a mapping of [build job, revision] -> list of downstream jobs to be triggered when that job is done
- Pulse actions listens for builds finishing (it might be one of its multiple listeners)
- Whenever a build finishes, we see if it matches one of our entries, if it matches, we trigger the list of jobs

Other listeners could interact with that by adding entries to the mapping.

**Comment by vaibhavmagarwal** [comment]
So here is my thinking:

1. When "trigger_missing_jobs" action arrives on exchange/treeherder/v1/job-actions , we will trigger

**Comment by vaibhavmagarwal** [comment]
So here is my thinking:

1. When "trigger_missing_jobs" action arrives on exchange/treeherder/v1/job-actions , we will trigger via "trigger_missing_jobs_for_revision" function in mozci:
    ** the downstream jobs for which an upstream build exists
    ** missing upstream jobs
2. We will then track the upstream jobs on exchange/builds for completion (yet to be built)
3. When the build completes, we will again call "trigger_missing_jobs_for_revision" function in mozci to trigger:
  ** downstream jobs for which upstream build exists

Note: We will be ensuring that there is one instance for each job.

@armenzg @adusca @chmanchester am I thinking in the right direction? Is there a flaw in this approach?

**Comment by adusca** [comment]
That would work. I think having a queueing functionality would be faster and would also be useful for other projects that just want to trigger a subset of the missing jobs when a job is finished.

That way trigger_missing_jobs could add to the mapping all the builds that are not ready and a list of every downstream job for each build.

**Comment by armenzg** [comment]
It sounds good to me.
The first time a revision is flagged, we can keep monitoring it until done.

A queuing system inside of mozci would also work and have longer term
potential.

At this point, either way would work. However, the queuing system is
something that IIUC  @chmanchester has added something similar to his
triggerbot. With that, I want to say that we might want to put it in
place so no more tools need to track jobs. Perhaps it can be its own
python library which we can re-share.

Whatever you choose, let us know if you find any blockers and need to
revise anything.

**Comment by vaibhavmagarwal** [comment]
After discussing with @chmanchester:
We have come to the conclusion that we do not need to store the [build job, revision] -> list of downstream jobs map. Reasons:
** We need to maintain a persistent database. We cannot afford to loose the queues in case heroku/aws goes down. This will require time and effort.
** We have have a map of builds->list of jobs in allthethings.json in mozci. We have functions like trigger_missing_jobs_for_revision, trigger_talos_jobs (all_talos) that are expected to trigger appropriate buildernames. They just require (revision, branch) as function arguments. In future, if someone wants to trigger a "particular" list of jobs, they can put the buildernames in a list and pass it to mozci.

So then what do we need in pulse_actions when a upstream build completes currently? We need just the (branch, revision) and the "function_name" that we need to call in mozci. Again as we did not want to go through the hassle of maintaining a persistent database, we looked for a bit hacky, but workable solution. We have the ability of passing "extra_properties" to upstream builders, we can attach something like {"function": "trigger_missing_jobs_for_revision"} when we send the payload to trigger_arbitrary_job (this function is called to trigger builds) and thankfully this parameter is passed back in the pulse exchange when the build is completed. We can also pass it {"buildernames_list": [list_of_buildernames]} in future if there is a need. Since this pulse exchange also contains: (revision, branch), we can directly call the function in mozci, without maintaining queues etc.

PS: tested the extra_properties approach, it is working fine.

@armenzg @adusca what do you think of this approach? Let me know your views.

**Comment by armenzg** [comment]
That's very creative!
Could you name the property something that would identify our system? (e.g. pulse_actions_function)
That way people would be a bit less confused.

Sidoe note, also be aware that we can have properties being truncated (it might only happen for very long properties) https://bugzilla.mozilla.org/show_bug.cgi?id=1187284

With regards to persistent database, the TaskCluster team uses a dirt cheap system (tens of thousands of messages for cents) to read/write in Azure if I recall correctly. I think I should disseminate this info in case we would like to use that.

**Comment by armenzg** [comment]
We can live without this.
