### ISSUE TITLE
add feature to duplicate talos jobs on pgo

### ISSUE THREAD

**Issue by jmaher** [mozilla/pulse_actions#70]
when we do a pgo build on mozilla-inbound or fx-team, I would like to ensure that we run talos jobs twice.  This would probably be similar to the logic for retriggering a failed job on try, or maybe the --rebuild option from a try run.  

The main reason for this is to ensure we have enough data to get alerts in a timely manner.  PGO alerts come much later than opt alerts and create unnecessary randomization.

**Comment by martiansideofthemoon** [comment]
Hey, could I work on this @armenzg ?

**Comment by armenzg** [comment]
Are you familiar with Pulse?
I will work on editing one of the videos on hacking pulse_actions so you can see how to set it up. It's better than reading the docs (they need some improving).

In short, read this:
https://github.com/mozilla/pulse_actions#how-it-works
https://github.com/mozilla/pulse_actions#running
https://github.com/mozilla/pulse_actions/blob/master/hello_world.md

You will need to create a handler (look under pulse_actions/handler for examples) that will read for Buildbot jobs completing (Unfortunately this will require changing in the future once TaskCluster takes care of PGO builds which will take a couple of quarters more).
chmanchester sets this consumer in here:
https://github.com/chmanchester/trigger-bot/blob/master/triggerbot/triggerbot_pulse.py#L154
Which I believe it is the same as the *normalized* buildbot stream:
https://wiki.mozilla.org/Auto-tools/Projects/Pulse/Exchanges#Normalized_BuildBot
Hit "start listening" to see the messages come in:
https://tools.taskcluster.net/pulse-inspector/#!%28%28exchange:exchange/build/normalized,routingKeyPattern:%23%29%29

You will then have to determine which jobs are PGO and call trigger_job() with times==2 for every talos build associated to such build:
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L383
Perhaps we need to split trigger_all_talos_jobs() to have an optional argument to indicate that we want all talos jobs for a specific build rather than all talos jobs that can be scheduled on a revision (see build_talos_buildernames_for_repo()):
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L561

To determine if a job is a 'pgo' build you can call get_buildername_metadata():
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/platforms.py#L232
You can then inspect the return type:
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/platforms.py#L286

Fortunately, by the time you hear about a PGO build completing you will have some talos jobs already either pending or running. Thus, immediately being able to schedule extra talos jobs. This is because build jobs schedule test jobs before they complete since they run some tests after they have uploaded the Firefox binaries.

**Comment by armenzg** [comment]
@jmaher does this do what you wanted?
https://treeherder.mozilla.org/#/jobs?repo=fx-team&revision=8cf323be5c58b28d8719401ebb0ef63f1d71d000&filter-searchStr=pgo%20talos&group_state=expanded

**Comment by jmaher** [comment]
yes, lets close this bug!

**Comment by martiansideofthemoon** [comment]
@jmaher @armenzg some odd behaviour here [https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=4014fede870e2b2adef58375d42e3af7c0f301a5](https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=4014fede870e2b2adef58375d42e3af7c0f301a5)
Why didn't the talos jobs trigger twice for `Linux x64 pgo`? what am I missing here? It hasn't happened for other pushes in `mozilla-inbound` and `fx-team`

**Comment by jmaher** [comment]
that is odd, could it just be an error in the system (maybe pulse_actions
scheduled it, but buildbot dropped the requests, etc.)

**Comment by armenzg** [comment]
@martiansideofthemoon you can use the papertrail logs to investigate things like this. Let me know if you need a hand getting started.

Easier link to use:
https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=4014fede870e2b2adef58375d42e3af7c0f301a5&filter-searchStr=linux%20x64%20talos%20pgo&group_state=expanded

**Comment by martiansideofthemoon** [comment]
Seems to be working ok, let's close this @armenzg
